### ISSUE TITLE
Embedded style in Andorra flag changes color of Latvian flag

### ISSUE THREAD

**Issue by ropez** [linssen/country-flag-icons#8]
When all flags are shown together, the color of the Latvian flag is wrong. I located the error in the flag of Andorra, which changes the fill color of the "class=st1"

![image](https://user-images.githubusercontent.com/431220/218299667-2e741551-ded7-474e-8659-b96784a22c04.png)

**Comment by linssen** [comment]
That's an interesting problem. This project doesn't actually modify the flags, but simply gathers them all from Wikimedia. I'd suggest making an edit therein for Andorra. 

Otherwise, it'd be possible to add a second step to inline all of the styles rather than use classes.

**Comment by ropez** [comment]
I worked around the problem by rendering the flags as `<img>` tags (with data URL), instead of inline `<svg>`, thus encapsulating the styling of each flag.
